<?php
//模块名称
$name='Cms';
//模块中文名称
$title='内容管理模块';
//模块描述
$description='内容管理模块';
//模块版本
$version='1.0.1';
//作者
$author='mushu';
//作者主页
$author_site='http://www.daydaytc.com/';
//作者邮箱
$author_email='929975447@qq.com';
//是否允许配置
$is_config=0;
//配置（序列化数组）
$config='';
//依赖模块
$rely_module=array();
//依赖插件
$rely_addons=array();